05-20 08:45:28 [ERROR] nonebot | Failed to import "modules.test_nb2"
Traceback (most recent call last):

  File "D:\Kira\run.py", line 7, in <module>
    bot.run(loop=loop)
    │   │        └ <ProactorEventLoop running=False closed=False debug=False>
    │   └ <function KiraBot.run at 0x0000026161682290>
    └ <kirabot.KiraBot object at 0x000002615E963730>

  File "D:\Kira\kirabot\__init__.py", line 46, in run
    self.init(**kwargs)
    │    │      └ {'loop': <ProactorEventLoop running=False closed=False debug=False>}
    │    └ <function KiraBot.init at 0x0000026161682200>
    └ <kirabot.KiraBot object at 0x000002615E963730>

  File "D:\Kira\kirabot\__init__.py", line 34, in init
    nonebot.load_plugin(f'modules.{module_name}')
    │       └ <function load_plugin at 0x000002616157C670>
    └ <module 'nonebot' from 'D:\\Kira\\venv\\lib\\site-packages\\nonebot\\__init__.py'>

  File "D:\Kira\venv\lib\site-packages\nonebot\plugin\load.py", line 28, in load_plugin
    return manager.load_plugin(module_path)
           │       │           └ 'modules.test_nb2'
           │       └ <function PluginManager.load_plugin at 0x0000026161567C70>
           └ <nonebot.plugin.manager.PluginManager object at 0x00000261624B4D60>

> File "D:\Kira\venv\lib\site-packages\nonebot\plugin\manager.py", line 104, in load_plugin
    module = importlib.import_module(name)
             │         │             └ 'modules.test_nb2'
             │         └ <function import_module at 0x000002615E6C4A60>
             └ <module 'importlib' from 'C:\\Python310\\lib\\importlib\\__init__.py'>

  File "C:\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'modules.test_nb2'
           │          └ <function _gcd_import at 0x000002615E1B3490>
           └ <module '_frozen_importlib' (frozen)>

  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked

  File "D:\Kira\venv\lib\site-packages\nonebot\plugin\manager.py", line 194, in exec_module
    super().exec_module(module)
                        └ <module 'modules.test_nb2' from 'D:\\Kira\\modules\\test_nb2\\__init__.py'>

  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "D:\Kira\modules\test_nb2\__init__.py", line 4, in <module>
    from kirabot.module import Module

  File "D:\Kira\kirabot\module.py", line 16, in <module>
    from .handler import NOTICE_TYPE

  File "D:\Kira\kirabot\handler.py", line 9, in <module>
    from .module import _loaded_modules, Module

ImportError: cannot import name '_loaded_modules' from partially initialized module 'kirabot.module' (most likely due to a circular import) (D:\Kira\kirabot\module.py)
